// AUTO-GENERATED by scripts/gen-types.mjs — do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      agencies: {
        Row: {
          id: string
          slug: string
          name: string
          tagline: string | null
          phone: string | null
          whatsapp: string | null
          email: string | null
          brand: Json
          settings: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          tagline?: string | null
          phone?: string | null
          whatsapp?: string | null
          email?: string | null
          brand?: Json
          settings?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          tagline?: string | null
          phone?: string | null
          whatsapp?: string | null
          email?: string | null
          brand?: Json
          settings?: Json
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      audit_log: {
        Row: {
          id: number
          agency_id: string | null
          actor_id: string | null
          action: string
          target_table: string
          target_id: string | null
          previous_value: Json | null
          new_value: Json | null
          created_at: string
        }
        Insert: {
          id?: number
          agency_id?: string | null
          actor_id?: string | null
          action: string
          target_table: string
          target_id?: string | null
          previous_value?: Json | null
          new_value?: Json | null
          created_at?: string
        }
        Update: {
          id?: number
          agency_id?: string | null
          actor_id?: string | null
          action?: string
          target_table?: string
          target_id?: string | null
          previous_value?: Json | null
          new_value?: Json | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'audit_log_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          }
        ]
      }
      booking_requests: {
        Row: {
          id: string
          agency_id: string
          client_id: string
          staff_id: string | null
          category_id: string | null
          status: Database['public']['Enums']['booking_status']
          live_arrangement: Database['public']['Enums']['live_arrangement'] | null
          start_date: string | null
          location_text: string | null
          notes: string | null
          created_at: string
          updated_at: string
          budget: number | null
          cancelled_reason: string | null
        }
        Insert: {
          id?: string
          agency_id: string
          client_id: string
          staff_id?: string | null
          category_id?: string | null
          status?: Database['public']['Enums']['booking_status']
          live_arrangement?: Database['public']['Enums']['live_arrangement'] | null
          start_date?: string | null
          location_text?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
          budget?: number | null
          cancelled_reason?: string | null
        }
        Update: {
          id?: string
          agency_id?: string
          client_id?: string
          staff_id?: string | null
          category_id?: string | null
          status?: Database['public']['Enums']['booking_status']
          live_arrangement?: Database['public']['Enums']['live_arrangement'] | null
          start_date?: string | null
          location_text?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
          budget?: number | null
          cancelled_reason?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'booking_requests_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'booking_requests_category_id_fkey'
            columns: ['category_id']
            isOneToOne: false
            referencedRelation: 'staff_categories'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'booking_requests_client_id_fkey'
            columns: ['client_id']
            isOneToOne: false
            referencedRelation: 'clients'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'booking_requests_staff_id_fkey'
            columns: ['staff_id']
            isOneToOne: false
            referencedRelation: 'staff_profiles'
            referencedColumns: ['id']
          }
        ]
      }
      clients: {
        Row: {
          id: string
          agency_id: string
          user_id: string
          name: string | null
          phone: string | null
          email: string | null
          location_text: string | null
          lat: number | null
          lng: number | null
          kind: Database['public']['Enums']['client_kind']
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          agency_id: string
          user_id: string
          name?: string | null
          phone?: string | null
          email?: string | null
          location_text?: string | null
          lat?: number | null
          lng?: number | null
          kind?: Database['public']['Enums']['client_kind']
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          agency_id?: string
          user_id?: string
          name?: string | null
          phone?: string | null
          email?: string | null
          location_text?: string | null
          lat?: number | null
          lng?: number | null
          kind?: Database['public']['Enums']['client_kind']
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'clients_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          }
        ]
      }
      contract_templates: {
        Row: {
          id: string
          agency_id: string
          version: number
          name: string
          body: string
          defaults: Json
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          agency_id: string
          version: number
          name: string
          body: string
          defaults?: Json
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          agency_id?: string
          version?: number
          name?: string
          body?: string
          defaults?: Json
          is_active?: boolean
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'contract_templates_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          }
        ]
      }
      contracts: {
        Row: {
          id: string
          agency_id: string
          booking_request_id: string
          template_id: string | null
          template_version: number | null
          terms_json: Json
          rate: number | null
          rate_period: Database['public']['Enums']['rate_period'] | null
          starts_on: string | null
          ends_on: string | null
          client_signature: string | null
          client_signed_at: string | null
          client_ip: string | null
          admin_signature: string | null
          admin_signed_at: string | null
          admin_signed_by: string | null
          pdf_url: string | null
          status: Database['public']['Enums']['contract_status']
          created_at: string
          updated_at: string
          amount_due: number | null
          duties: string | null
          live_arrangement: Database['public']['Enums']['live_arrangement'] | null
          ended_at: string | null
          end_reason: string | null
        }
        Insert: {
          id?: string
          agency_id: string
          booking_request_id: string
          template_id?: string | null
          template_version?: number | null
          terms_json?: Json
          rate?: number | null
          rate_period?: Database['public']['Enums']['rate_period'] | null
          starts_on?: string | null
          ends_on?: string | null
          client_signature?: string | null
          client_signed_at?: string | null
          client_ip?: string | null
          admin_signature?: string | null
          admin_signed_at?: string | null
          admin_signed_by?: string | null
          pdf_url?: string | null
          status?: Database['public']['Enums']['contract_status']
          created_at?: string
          updated_at?: string
          amount_due?: number | null
          duties?: string | null
          live_arrangement?: Database['public']['Enums']['live_arrangement'] | null
          ended_at?: string | null
          end_reason?: string | null
        }
        Update: {
          id?: string
          agency_id?: string
          booking_request_id?: string
          template_id?: string | null
          template_version?: number | null
          terms_json?: Json
          rate?: number | null
          rate_period?: Database['public']['Enums']['rate_period'] | null
          starts_on?: string | null
          ends_on?: string | null
          client_signature?: string | null
          client_signed_at?: string | null
          client_ip?: string | null
          admin_signature?: string | null
          admin_signed_at?: string | null
          admin_signed_by?: string | null
          pdf_url?: string | null
          status?: Database['public']['Enums']['contract_status']
          created_at?: string
          updated_at?: string
          amount_due?: number | null
          duties?: string | null
          live_arrangement?: Database['public']['Enums']['live_arrangement'] | null
          ended_at?: string | null
          end_reason?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'contracts_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'contracts_booking_request_id_fkey'
            columns: ['booking_request_id']
            isOneToOne: false
            referencedRelation: 'booking_requests'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'contracts_template_id_fkey'
            columns: ['template_id']
            isOneToOne: false
            referencedRelation: 'contract_templates'
            referencedColumns: ['id']
          }
        ]
      }
      existing_staff_claims: {
        Row: {
          id: string
          agency_id: string
          client_id: string
          staff_full_name_freeform: string
          staff_phone_freeform: string | null
          notes: string | null
          agency_confirmed_staff_id: string | null
          status: Database['public']['Enums']['claim_status']
          reviewed_by: string | null
          reviewed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          agency_id: string
          client_id: string
          staff_full_name_freeform: string
          staff_phone_freeform?: string | null
          notes?: string | null
          agency_confirmed_staff_id?: string | null
          status?: Database['public']['Enums']['claim_status']
          reviewed_by?: string | null
          reviewed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          agency_id?: string
          client_id?: string
          staff_full_name_freeform?: string
          staff_phone_freeform?: string | null
          notes?: string | null
          agency_confirmed_staff_id?: string | null
          status?: Database['public']['Enums']['claim_status']
          reviewed_by?: string | null
          reviewed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'existing_staff_claims_agency_confirmed_staff_id_fkey'
            columns: ['agency_confirmed_staff_id']
            isOneToOne: false
            referencedRelation: 'staff_profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'existing_staff_claims_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'existing_staff_claims_client_id_fkey'
            columns: ['client_id']
            isOneToOne: false
            referencedRelation: 'clients'
            referencedColumns: ['id']
          }
        ]
      }
      job_applications: {
        Row: {
          id: string
          agency_id: string
          vacancy_id: string | null
          applicant_user_id: string | null
          full_name: string
          phone: string
          email: string | null
          location_text: string | null
          date_of_birth: string | null
          years_experience: number | null
          skills: string[]
          languages: string[]
          cover_note: string | null
          engagement: Database['public']['Enums']['engagement_preference']
          preferred_terms: string | null
          expected_pay: number | null
          expected_pay_period: Database['public']['Enums']['rate_period'] | null
          documents: Json
          consent_at: string
          status: Database['public']['Enums']['application_status']
          admin_notes: string | null
          reviewed_by: string | null
          reviewed_at: string | null
          staff_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          agency_id: string
          vacancy_id?: string | null
          applicant_user_id?: string | null
          full_name: string
          phone: string
          email?: string | null
          location_text?: string | null
          date_of_birth?: string | null
          years_experience?: number | null
          skills?: string[]
          languages?: string[]
          cover_note?: string | null
          engagement: Database['public']['Enums']['engagement_preference']
          preferred_terms?: string | null
          expected_pay?: number | null
          expected_pay_period?: Database['public']['Enums']['rate_period'] | null
          documents?: Json
          consent_at?: string
          status?: Database['public']['Enums']['application_status']
          admin_notes?: string | null
          reviewed_by?: string | null
          reviewed_at?: string | null
          staff_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          agency_id?: string
          vacancy_id?: string | null
          applicant_user_id?: string | null
          full_name?: string
          phone?: string
          email?: string | null
          location_text?: string | null
          date_of_birth?: string | null
          years_experience?: number | null
          skills?: string[]
          languages?: string[]
          cover_note?: string | null
          engagement?: Database['public']['Enums']['engagement_preference']
          preferred_terms?: string | null
          expected_pay?: number | null
          expected_pay_period?: Database['public']['Enums']['rate_period'] | null
          documents?: Json
          consent_at?: string
          status?: Database['public']['Enums']['application_status']
          admin_notes?: string | null
          reviewed_by?: string | null
          reviewed_at?: string | null
          staff_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'job_applications_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'job_applications_staff_id_fkey'
            columns: ['staff_id']
            isOneToOne: false
            referencedRelation: 'staff_profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'job_applications_vacancy_id_fkey'
            columns: ['vacancy_id']
            isOneToOne: false
            referencedRelation: 'vacancies'
            referencedColumns: ['id']
          }
        ]
      }
      leads: {
        Row: {
          id: string
          agency_id: string
          name: string | null
          phone: string | null
          email: string | null
          need: string
          area: string | null
          start_date: string | null
          budget: string | null
          source: string
          transcript: Json | null
          status: Database['public']['Enums']['lead_status']
          admin_notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          agency_id: string
          name?: string | null
          phone?: string | null
          email?: string | null
          need: string
          area?: string | null
          start_date?: string | null
          budget?: string | null
          source?: string
          transcript?: Json | null
          status?: Database['public']['Enums']['lead_status']
          admin_notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          agency_id?: string
          name?: string | null
          phone?: string | null
          email?: string | null
          need?: string
          area?: string | null
          start_date?: string | null
          budget?: string | null
          source?: string
          transcript?: Json | null
          status?: Database['public']['Enums']['lead_status']
          admin_notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'leads_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          }
        ]
      }
      match_queries: {
        Row: {
          id: number
          agency_id: string
          user_id: string | null
          query: string
          category_slug: string | null
          area: string | null
          results: number
          engine: string
          created_at: string
        }
        Insert: {
          id?: number
          agency_id: string
          user_id?: string | null
          query: string
          category_slug?: string | null
          area?: string | null
          results?: number
          engine: string
          created_at?: string
        }
        Update: {
          id?: number
          agency_id?: string
          user_id?: string | null
          query?: string
          category_slug?: string | null
          area?: string | null
          results?: number
          engine?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'match_queries_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          }
        ]
      }
      message_threads: {
        Row: {
          id: string
          agency_id: string
          client_id: string
          booking_request_id: string | null
          subject: string | null
          last_message_at: string
          created_at: string
          kind: Database['public']['Enums']['thread_kind']
          status: Database['public']['Enums']['thread_status']
          resolved_at: string | null
          staff_id: string | null
          claim_id: string | null
          client_last_read_at: string
          admin_last_read_at: string
        }
        Insert: {
          id?: string
          agency_id: string
          client_id: string
          booking_request_id?: string | null
          subject?: string | null
          last_message_at?: string
          created_at?: string
          kind?: Database['public']['Enums']['thread_kind']
          status?: Database['public']['Enums']['thread_status']
          resolved_at?: string | null
          staff_id?: string | null
          claim_id?: string | null
          client_last_read_at?: string
          admin_last_read_at?: string
        }
        Update: {
          id?: string
          agency_id?: string
          client_id?: string
          booking_request_id?: string | null
          subject?: string | null
          last_message_at?: string
          created_at?: string
          kind?: Database['public']['Enums']['thread_kind']
          status?: Database['public']['Enums']['thread_status']
          resolved_at?: string | null
          staff_id?: string | null
          claim_id?: string | null
          client_last_read_at?: string
          admin_last_read_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'message_threads_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'message_threads_booking_request_id_fkey'
            columns: ['booking_request_id']
            isOneToOne: false
            referencedRelation: 'booking_requests'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'message_threads_claim_id_fkey'
            columns: ['claim_id']
            isOneToOne: false
            referencedRelation: 'existing_staff_claims'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'message_threads_client_id_fkey'
            columns: ['client_id']
            isOneToOne: false
            referencedRelation: 'clients'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'message_threads_staff_id_fkey'
            columns: ['staff_id']
            isOneToOne: false
            referencedRelation: 'staff_profiles'
            referencedColumns: ['id']
          }
        ]
      }
      messages: {
        Row: {
          id: string
          thread_id: string
          sender_id: string
          sender_role: Database['public']['Enums']['user_role']
          body: string
          created_at: string
        }
        Insert: {
          id?: string
          thread_id: string
          sender_id: string
          sender_role: Database['public']['Enums']['user_role']
          body: string
          created_at?: string
        }
        Update: {
          id?: string
          thread_id?: string
          sender_id?: string
          sender_role?: Database['public']['Enums']['user_role']
          body?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'messages_thread_id_fkey'
            columns: ['thread_id']
            isOneToOne: false
            referencedRelation: 'message_threads'
            referencedColumns: ['id']
          }
        ]
      }
      notifications: {
        Row: {
          id: string
          agency_id: string
          type: Database['public']['Enums']['notification_type']
          message: string
          link: string | null
          target_user_id: string | null
          target_role: Database['public']['Enums']['user_role'] | null
          read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          agency_id: string
          type: Database['public']['Enums']['notification_type']
          message: string
          link?: string | null
          target_user_id?: string | null
          target_role?: Database['public']['Enums']['user_role'] | null
          read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          agency_id?: string
          type?: Database['public']['Enums']['notification_type']
          message?: string
          link?: string | null
          target_user_id?: string | null
          target_role?: Database['public']['Enums']['user_role'] | null
          read?: boolean
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'notifications_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          }
        ]
      }
      payments: {
        Row: {
          id: string
          agency_id: string
          contract_id: string
          amount: number
          currency: string
          method: Database['public']['Enums']['payment_method']
          payer_phone: string | null
          mpesa_checkout_request_id: string | null
          mpesa_receipt: string | null
          card_ref: string | null
          status: Database['public']['Enums']['payment_status']
          paid_at: string | null
          raw_callback: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          agency_id: string
          contract_id: string
          amount: number
          currency?: string
          method: Database['public']['Enums']['payment_method']
          payer_phone?: string | null
          mpesa_checkout_request_id?: string | null
          mpesa_receipt?: string | null
          card_ref?: string | null
          status?: Database['public']['Enums']['payment_status']
          paid_at?: string | null
          raw_callback?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          agency_id?: string
          contract_id?: string
          amount?: number
          currency?: string
          method?: Database['public']['Enums']['payment_method']
          payer_phone?: string | null
          mpesa_checkout_request_id?: string | null
          mpesa_receipt?: string | null
          card_ref?: string | null
          status?: Database['public']['Enums']['payment_status']
          paid_at?: string | null
          raw_callback?: Json | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'payments_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'payments_contract_id_fkey'
            columns: ['contract_id']
            isOneToOne: false
            referencedRelation: 'contracts'
            referencedColumns: ['id']
          }
        ]
      }
      profiles: {
        Row: {
          id: string
          agency_id: string
          role: Database['public']['Enums']['user_role']
          full_name: string | null
          email: string | null
          phone: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          agency_id: string
          role?: Database['public']['Enums']['user_role']
          full_name?: string | null
          email?: string | null
          phone?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          agency_id?: string
          role?: Database['public']['Enums']['user_role']
          full_name?: string | null
          email?: string | null
          phone?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'profiles_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          }
        ]
      }
      push_tokens: {
        Row: {
          id: string
          user_id: string
          token: string
          platform: string | null
          created_at: string
          last_seen_at: string
        }
        Insert: {
          id?: string
          user_id: string
          token: string
          platform?: string | null
          created_at?: string
          last_seen_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          token?: string
          platform?: string | null
          created_at?: string
          last_seen_at?: string
        }
        Relationships: []
      }
      ratings: {
        Row: {
          id: string
          agency_id: string
          contract_id: string | null
          claim_id: string | null
          client_id: string
          staff_id: string
          stars: number
          comment: string | null
          is_published: boolean
          moderated_by: string | null
          moderated_at: string | null
          created_at: string
          admin_note: string | null
        }
        Insert: {
          id?: string
          agency_id: string
          contract_id?: string | null
          claim_id?: string | null
          client_id: string
          staff_id: string
          stars: number
          comment?: string | null
          is_published?: boolean
          moderated_by?: string | null
          moderated_at?: string | null
          created_at?: string
          admin_note?: string | null
        }
        Update: {
          id?: string
          agency_id?: string
          contract_id?: string | null
          claim_id?: string | null
          client_id?: string
          staff_id?: string
          stars?: number
          comment?: string | null
          is_published?: boolean
          moderated_by?: string | null
          moderated_at?: string | null
          created_at?: string
          admin_note?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'ratings_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'ratings_claim_id_fkey'
            columns: ['claim_id']
            isOneToOne: false
            referencedRelation: 'existing_staff_claims'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'ratings_client_id_fkey'
            columns: ['client_id']
            isOneToOne: false
            referencedRelation: 'clients'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'ratings_contract_id_fkey'
            columns: ['contract_id']
            isOneToOne: false
            referencedRelation: 'contracts'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'ratings_staff_id_fkey'
            columns: ['staff_id']
            isOneToOne: false
            referencedRelation: 'staff_profiles'
            referencedColumns: ['id']
          }
        ]
      }
      staff_categories: {
        Row: {
          id: string
          agency_id: string
          name: string
          slug: string
          description: string | null
          icon: string | null
          image_url: string | null
          sort_order: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          agency_id: string
          name: string
          slug: string
          description?: string | null
          icon?: string | null
          image_url?: string | null
          sort_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          agency_id?: string
          name?: string
          slug?: string
          description?: string | null
          icon?: string | null
          image_url?: string | null
          sort_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'staff_categories_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          }
        ]
      }
      staff_profiles: {
        Row: {
          id: string
          agency_id: string
          user_id: string | null
          category_id: string
          full_name: string
          photo_url: string | null
          video_url: string | null
          bio: string | null
          skills: string[]
          languages: string[]
          location_text: string | null
          lat: number | null
          lng: number | null
          availability: Database['public']['Enums']['staff_availability']
          live_arrangement: Database['public']['Enums']['live_arrangement']
          day_rate: number | null
          month_rate: number | null
          years_experience: number | null
          vetting_status: Database['public']['Enums']['vetting_status']
          id_doc_url: string | null
          verified_badge: boolean
          trained_badge: boolean
          background_checked_badge: boolean
          rating_avg: number
          rating_count: number
          is_active: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          agency_id: string
          user_id?: string | null
          category_id: string
          full_name: string
          photo_url?: string | null
          video_url?: string | null
          bio?: string | null
          skills?: string[]
          languages?: string[]
          location_text?: string | null
          lat?: number | null
          lng?: number | null
          availability?: Database['public']['Enums']['staff_availability']
          live_arrangement?: Database['public']['Enums']['live_arrangement']
          day_rate?: number | null
          month_rate?: number | null
          years_experience?: number | null
          vetting_status?: Database['public']['Enums']['vetting_status']
          id_doc_url?: string | null
          verified_badge?: boolean
          trained_badge?: boolean
          background_checked_badge?: boolean
          rating_avg?: number
          rating_count?: number
          is_active?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          agency_id?: string
          user_id?: string | null
          category_id?: string
          full_name?: string
          photo_url?: string | null
          video_url?: string | null
          bio?: string | null
          skills?: string[]
          languages?: string[]
          location_text?: string | null
          lat?: number | null
          lng?: number | null
          availability?: Database['public']['Enums']['staff_availability']
          live_arrangement?: Database['public']['Enums']['live_arrangement']
          day_rate?: number | null
          month_rate?: number | null
          years_experience?: number | null
          vetting_status?: Database['public']['Enums']['vetting_status']
          id_doc_url?: string | null
          verified_badge?: boolean
          trained_badge?: boolean
          background_checked_badge?: boolean
          rating_avg?: number
          rating_count?: number
          is_active?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'staff_profiles_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'staff_profiles_category_id_fkey'
            columns: ['category_id']
            isOneToOne: false
            referencedRelation: 'staff_categories'
            referencedColumns: ['id']
          }
        ]
      }
      staff_vetting_checks: {
        Row: {
          id: string
          agency_id: string
          staff_id: string
          check_type: Database['public']['Enums']['vetting_check_type']
          passed: boolean
          notes: string | null
          confirmed_by: string | null
          confirmed_at: string
        }
        Insert: {
          id?: string
          agency_id: string
          staff_id: string
          check_type: Database['public']['Enums']['vetting_check_type']
          passed?: boolean
          notes?: string | null
          confirmed_by?: string | null
          confirmed_at?: string
        }
        Update: {
          id?: string
          agency_id?: string
          staff_id?: string
          check_type?: Database['public']['Enums']['vetting_check_type']
          passed?: boolean
          notes?: string | null
          confirmed_by?: string | null
          confirmed_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'staff_vetting_checks_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'staff_vetting_checks_staff_id_fkey'
            columns: ['staff_id']
            isOneToOne: false
            referencedRelation: 'staff_profiles'
            referencedColumns: ['id']
          }
        ]
      }
      vacancies: {
        Row: {
          id: string
          agency_id: string
          category_id: string | null
          title: string
          description: string
          requirements: string | null
          location_text: string | null
          employment_type: Database['public']['Enums']['employment_type']
          live_arrangement: Database['public']['Enums']['live_arrangement']
          pay_min: number | null
          pay_max: number | null
          pay_period: Database['public']['Enums']['rate_period']
          positions: number
          required_documents: string[]
          closes_on: string | null
          status: Database['public']['Enums']['vacancy_status']
          created_by: string | null
          published_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          agency_id: string
          category_id?: string | null
          title: string
          description: string
          requirements?: string | null
          location_text?: string | null
          employment_type?: Database['public']['Enums']['employment_type']
          live_arrangement?: Database['public']['Enums']['live_arrangement']
          pay_min?: number | null
          pay_max?: number | null
          pay_period?: Database['public']['Enums']['rate_period']
          positions?: number
          required_documents?: string[]
          closes_on?: string | null
          status?: Database['public']['Enums']['vacancy_status']
          created_by?: string | null
          published_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          agency_id?: string
          category_id?: string | null
          title?: string
          description?: string
          requirements?: string | null
          location_text?: string | null
          employment_type?: Database['public']['Enums']['employment_type']
          live_arrangement?: Database['public']['Enums']['live_arrangement']
          pay_min?: number | null
          pay_max?: number | null
          pay_period?: Database['public']['Enums']['rate_period']
          positions?: number
          required_documents?: string[]
          closes_on?: string | null
          status?: Database['public']['Enums']['vacancy_status']
          created_by?: string | null
          published_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'vacancies_agency_id_fkey'
            columns: ['agency_id']
            isOneToOne: false
            referencedRelation: 'agencies'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'vacancies_category_id_fkey'
            columns: ['category_id']
            isOneToOne: false
            referencedRelation: 'staff_categories'
            referencedColumns: ['id']
          }
        ]
      }
    }
    Views: {
      staff_catalog: {
        Row: {
          id: string | null
          agency_id: string | null
          category_id: string | null
          category_name: string | null
          category_slug: string | null
          full_name: string | null
          photo_url: string | null
          video_url: string | null
          bio: string | null
          skills: string[] | null
          languages: string[] | null
          location_text: string | null
          approx_lat: number | null
          approx_lng: number | null
          availability: Database['public']['Enums']['staff_availability'] | null
          live_arrangement: Database['public']['Enums']['live_arrangement'] | null
          day_rate: number | null
          month_rate: number | null
          years_experience: number | null
          verified_badge: boolean | null
          trained_badge: boolean | null
          background_checked_badge: boolean | null
          rating_avg: number | null
          rating_count: number | null
        }
        Relationships: []
      }
      staff_reviews: {
        Row: {
          id: string | null
          agency_id: string | null
          staff_id: string | null
          stars: number | null
          comment: string | null
          client_first_name: string | null
          client_area: string | null
          created_at: string | null
        }
        Relationships: []
      }
      testimonials: {
        Row: {
          id: string | null
          agency_id: string | null
          stars: number | null
          comment: string | null
          client_first_name: string | null
          client_area: string | null
          category_name: string | null
          created_at: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      hit_rate_limit: {
        Args: {
          p_key: string
          p_limit: number
          p_window_seconds: number
        }
        Returns: boolean
      }
    }
    Enums: {
      application_status: 'new' | 'reviewing' | 'shortlisted' | 'interview' | 'accepted' | 'rejected' | 'withdrawn'
      booking_status: 'pending' | 'matched' | 'contracted' | 'active' | 'completed' | 'cancelled'
      claim_status: 'pending' | 'confirmed' | 'rejected'
      client_kind: 'household' | 'business'
      contract_status: 'draft' | 'sent' | 'client_signed' | 'fully_signed' | 'active' | 'ended' | 'cancelled'
      employment_type: 'full_time' | 'part_time' | 'contract' | 'temporary' | 'casual'
      engagement_preference: 'join_agency' | 'own_terms'
      lead_status: 'new' | 'contacted' | 'converted' | 'closed'
      live_arrangement: 'live_in' | 'live_out' | 'either'
      notification_type: 'new_request' | 'matched' | 'contract_ready' | 'payment_received' | 'rating_submitted' | 'replacement_requested' | 'dispute_raised' | 'new_application' | 'contract_signed' | 'booking_update' | 'new_message' | 'claim_update'
      payment_method: 'mpesa' | 'card' | 'cash' | 'bank'
      payment_status: 'pending' | 'processing' | 'paid' | 'failed' | 'refunded'
      rate_period: 'day' | 'month'
      staff_availability: 'available' | 'placed' | 'unavailable'
      thread_kind: 'general' | 'replacement' | 'dispute' | 'extension' | 'end_request'
      thread_status: 'open' | 'resolved'
      user_role: 'super_admin' | 'staff' | 'client'
      vacancy_status: 'draft' | 'open' | 'closed' | 'filled'
      vetting_check_type: 'id_verification' | 'reference_check' | 'background_check' | 'training'
      vetting_status: 'pending' | 'in_review' | 'verified' | 'rejected'
    }
    CompositeTypes: Record<string, never>
  }
}

type PublicSchema = Database['public']
export type Tables<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Row']
export type TablesInsert<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Update']
export type Views<T extends keyof PublicSchema['Views']> = PublicSchema['Views'][T]['Row']
export type Enums<T extends keyof PublicSchema['Enums']> = PublicSchema['Enums'][T]
